### ISSUE TITLE
transmission.service: Failed to set up mount namespacing

### ISSUE THREAD

**Issue by raj-magesh** [rasmus-kirk/nixarr#35] opened 2024-07-31 07:18 UTC
**Describe the bug**

The following error when building my configuration:

```
Jul 31 03:10:47 desktop systemd[1]: Starting Transmission BitTorrent Service...
Jul 31 03:10:47 desktop (prestart)[184019]: transmission.service: Failed to set up mount namespacing: /data/nixarr/torrents/.incomplete: No such file or directory
Jul 31 03:10:47 desktop (prestart)[184019]: transmission.service: Failed at step NAMESPACE spawning /nix/store/xf8m2cfaj9ydqzg37fhvgja6cdxq1zdh-transmission-prestart: No such file or directory
Jul 31 03:10:47 desktop systemd[1]: transmission.service: Control process exited, code=exited, status=226/NAMESPACE
```

**To Reproduce**
1. Use the following minimal `nixarr` configuration:
```
{...}: {
  nixarr = {
    enable = true;
    mediaDir = "/data/nixarr";
    mediaUsers = ["redacted"];
    vpn = {
      enable = true;
      wgConf = "/persist/home/redacted/mullvad-us-qas-wg-001.conf";
    };
    transmission = {
      enable = true;
      stateDir = "/persist/nixarr/transmission";
    };
```
2. Rebuild and switch to a new NixOS configuration: `nix flake update /data/dotfiles && sudo nixos-rebuild switch --flake /data/dotfiles`
3. The build errors out

**Desktop (please complete the following information):**
 - OS: NixOS Unstable

**Additional context**
A similar issue is [reported here](https://github.com/NixOS/nixpkgs/issues/183429) and I think it should be fixed in upstream, but I'm not sure if there's something `nixarr` has to fix too.

**Comment by rasmus-kirk** [comment] 2024-08-06 08:31
> Going through other issues, this might be a dupe of #20

Does changing permissions to be more forgiving help? Otherwise it's not a dupe

**Comment by rasmus-kirk** [comment] 2024-08-26 12:15
> I realized `/data/nixarr` (my `mediaDir`) was created with owner `root`. I tried `chown`-ing it to my user, then rebuilding my NixOS config, but the ownership changed back to `root`.

This is by design, the subpath to nixarr must be owned by root. This is also [stated in the documentation](https://nixarr.com/options.html#nixarr.mediadir), see also the issue you linked #20. It should however not result in the error message that you're getting.

Try this:

```nix
{...}: {
  nixarr = {
    enable = true;
    mediaDir = "/nixarr";
    stateDir = "/nixarr/.state"
    mediaUsers = ["redacted"];
    vpn = {
      enable = true;
      wgConf = "/persist/home/redacted/mullvad-us-qas-wg-001.conf";
    };
    transmission = {
      enable = true;
    };
```

Then set impermanence to not delete the `/nixarr` dir.

**Comment by rasmus-kirk** [comment] 2024-09-26 09:13
Should be fixed upstream in the VPN-module

**Closed as completed by rasmus-kirk** 2024-09-26 09:13 UTC
